volumes:
  mongo_data:
  es_data:
  graylog_data:
  graylog_journal:

networks:
  default-network:
    name: default-network
    driver: bridge

services:
  mongo:
    image: "mongo:5.0"
    container_name: mongo
    networks:
      - default-network
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - default-network
    restart: unless-stopped

  graylog:
    image: "graylog/graylog:6.0.5"
    container_name: graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=
      - GRAYLOG_ROOT_PASSWORD_SHA2=
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    depends_on:
      - mongo
      - elasticsearch
    networks:
      - default-network
    ports:
      - "9000:9000"
      - "12201:12201/udp"
      - "5044:5044"
    volumes:
      - graylog_data:/usr/share/graylog/data
      - graylog_journal:/usr/share/graylog/data/journal
    restart: unless-stopped

